### ISSUE TITLE
exception in grab_cpu_cores()

### ISSUE THREAD

**Issue by ncoronges** [netmet1/constellation-node-automation#7]
Got this up and running, but was getting error on `grab_cpu_cores()`
Im on AWS ubuntu instance and /proc/cpuinfo returns no pattern match for "cpu cores" so float(result_stream.read()) throws an exception. i can do a pull request to fix but checking here first.

**Comment by netmet1** [comment]
Hey there!  Absolutely, that would be great if you wanted to make a fix!  I'm happy that you are interested in the project and would be appreciative of the assist!

**Comment by netmet1** [comment]
hey @ncoronges - quick question

Can you let me know which AMI you are using for AWS ubuntu?  I loaded up the free-tier `t2-micro` and I'm able to get a proper response from issuing the `cat /proc/cpuinfo | grep 'cpu cores' | awk '{print $4}' | tail -1` for the command line.  

I was seeing what needed to be done, I didn't want to let the issue sit open too long.

`ami-00399ec92321828f5`

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

Can you reproduce and show the output of the response that you are receiving?

**Comment by ncoronges** [comment]
Hey - 
Im on ami-0eaf674932ea3dfba

ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-arm64-server-20210512-10d15682-9d0b-41dd-93c2-5e7de4f74165

I do get the cpu core info from lscpu command, or:

`lscpu | grep '^CPU(s):' | awk '{print $2}' | tail -1`

keep me posted
